routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'web'], function () {

    Route::group(['namespace' => 'Frontend'], function () {

        Route::get('/pages/{slug}', 'HomeController@showPage');
        Route::get('/', 'HomeController@rootRedirection');

    });
});


Auth::routes();
Route::get('admin/errors/401',['as' => 'admin.errors', 'uses' =>  'DashboardController@errorsView']);

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'check-route-permission']], function () {

    Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'DashboardController@adminDashboard']);

    //Cache and composer autoload management
    Route::get('cache/management', ['as' => 'cache.management', 'uses' => 'DashboardController@cacheManagement']);

    Route::group(['namespace' => 'Admin'], function () {    

        // All user module route
        Route::get('user/active/{status?}/{uid?}', ['as' => 'user.status', 'uses' => 'UserController@updateUserStatus']);
        Route::resource('user', 'UserController');
        Route::post('user/roles', ['as' => 'user.userroles', 'uses' => 'UserController@storeUserRoles']);

        // All role module route
        Route::resource('role', 'RoleController');
        Route::post('role/competence', ['as' => 'role.competence', 'uses' => 'RoleController@storeCompetence']);

        // All permission module route
        Route::resource('permission', 'PermissionController');

        // All page module route
        Route::resource('page', 'PageBuilderController');

        // All theme setting module route
        Route::resource('theme', 'FrontendThemeController');

        // Create model view controller from admin side
        Route::resource('module', 'ModuleCreatorController');
        Route::get('module/active/{status?}/{mid?}', ['as' => 'module.status', 'uses' => 'ModuleCreatorController@updateModuleStatus']);

        // All log module route
        Route::get('log/downloads/{file_name?}', ['as' => 'log.downloads', 'uses' => 'LogController@downloads']);
        Route::resource('log', 'LogController');

        // All backup setting module route
        Route::get('backup/download/{file_name?}', ['as' => 'backup.download', 'uses' => 'BackupController@downloads']);
        Route::resource('backup', 'BackupController');

        // All backup setting module route
        Route::get('slider/showconfiguredslider', ['as' => 'slider.showconfiguredslider', 'uses' => 'SliderController@showConfiguredSlider']);
        Route::get('slider/addconfiguredslider', ['as' => 'slider.addconfiguredslider', 'uses' => 'SliderController@addConfiguredSlider']);
        Route::post('slider/addconfiguredslider', ['as' => 'slider.addconfiguredslider', 'uses' => 'SliderController@storeConfiguredSlider']);
        Route::resource('slider', 'SliderController');
        
        //Custom Modules
        $customModule = (new \App\ACME\MakeRoutes())->getModuleName();
        if($customModule != null) {
            foreach($customModule as $module) {
                Route::resource(strtolower($module->module_name), ucwords($module->module_name).'Controller');
            }
        }

    });
});

resources/views/layouts/admin/partial/admin-left-menus.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="{{url('admin')}}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            @if(Auth::user()->hasRole('administration'))
                <li>
                    <a href="#">
                        <i class="fa fa-users fa-fw"></i> User Management <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('user.index')}}">Users</a></li>
                        <li><a href="{{route('user.create')}}">Add User</a></li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-asl-interpreting fa-fw"></i> Roles
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('role.index') }}"> Roles</a></li>
                        <li><a href="{{route('role.create') }}"> Add Role</a></li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-user-secret fa-fw"></i> Permissions
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('permission.index') }}"> Permissions</a></li>
                        <li><a href="{{route('permission.create') }}"> Add Permission</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-pagelines fa-fw"></i> Page Builder
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('page.index') }}"> Pages</a></li>
                        <li><a href="{{route('page.create') }}"> Add Page</a></li>
                    </ul>
                </li>
                {{--<li>
                    <a href="#">
                        <i class="fa fa-file fa-fw"></i> Backup
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('backup.index') }}"> Backups</a></li>
                        <li><a href="{{route('backup.create') }}"> Create Backup</a></li>
                    </ul>
                </li>--}}
                <li>
                    <a href="#">
                        <i class="fa fa-angle-double-up fa-fw"></i> Module Creator
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('module.index') }}"> Modules</a></li>
                        <li><a href="{{route('module.create') }}"> Add Module</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-angle-double-up fa-fw"></i> Slider
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('slider.index') }}"> Sliders</a></li>
                        <li><a href="{{route('slider.create') }}"> Add Slider</a></li>
                        <li><a href="{{route('slider.showconfiguredslider') }}"> Show Sliders</a></li>
                        <li><a href="{{route('slider.addconfiguredslider') }}"> Configure Slider</a></li>
                    </ul>
                </li>

                @foreach($customModule as $module)
                    @if($module->active && $module->controller_related_to == 'Admin')
                        <li>
                            <a href="#">
                                &nbsp;<i class="fa fa-windows  fa-fw"></i> {{ $module->module_name}}
                                <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{url('admin/'.strtolower($module->module_name)) }}">
                                        {{$module->module_name}}s</a></li>
                                @if(Auth::user()->can(strtolower($module->module_name).'.create'))
                                    <li><a href="{{url('admin/'.strtolower($module->module_name).'/create') }}">
                                            Add {{$module->module_name}}</a></li>
                                @endif
                            </ul>
                        </li>
                    @endif
                @endforeach

            @endif
            <li>
                <a href="#">
                    <i class="fa fa-gear fa-fw"></i> Settings
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li><a href="{{route('theme.index') }}"> Update Theme </a></li>
                    <li><a href="{{route('cache.management') }}"> Clear Compiled & Views</a></li>
                    <li><a href="{{route('log.index') }}"> Logs </a></li>
                </ul>
            </li>
            <li ><a href="{{ route('logout') }}" onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();" class="text-danger"><i class="fa fa-sign-out"></i> Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                      style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>

resources/views/layouts/admin/partial/breadcrumb.blade.php
<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <div class="breadcrumb">
                <div class="active"><a href="{{ url('admin') }}">Dashboard</a>
                    @if($levelOne != null)
                        >>  @if($levelOneLink != null)
                            <a href="{{ url($levelOneLink) }}">{{$levelOne}}</a>
                        @else
                            <strong>  {{$levelOne}} </strong>
                        @endif
                    @endif
                    @if($levelTwo != null)
                        >>  @if($levelTwoLink != null)
                            <a href="{{ url($levelTwoLink) }}">{{$levelTwo}}</a>
                        @else
                            <strong>  {{$levelTwo}} </strong>
                        @endif
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/admin/partial/footer.blade.php
<div class="container" align="center">
	<small>&copy; Laravel Footer</small>
</div> 

resources/views/layouts/admin/partial/layout-css.blade.php
<!-- Bootstrap Core CSS -->
<link href="{{url('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
<!-- MetisMenu CSS -->
<link href="{{url('vendor/metisMenu/metisMenu.min.css')}}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{{url('dist/css/sb-admin-2.css')}}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{{url('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('jBox/Source/jBox.css')}}" rel="stylesheet" type="text/css">
<style>
    .page-header {
        padding-bottom: 0px !important;
        margin: 10px 0 20px;
        border-bottom: 1px solid #eee;
    }
</style>
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link href="{{url('dist/css/jquery.fileupload.css')}}" rel="stylesheet">
<link href="{{url('dist/css/jquery.fileupload-ui.css')}}" rel="stylesheet">
<!-- CSS adjustments for browsers with JavaScript disabled -->
<link href="{{url('dist/css/jquery.fileupload-noscript.css')}}" rel="stylesheet">
<link href="{{url('dist/css/jquery.fileupload-ui-noscript.css')}}" rel="stylesheet">
<!-- blueimp Gallery styles -->
<link href="{{url('dist/css/blueimp-gallery.min.css')}}" rel="stylesheet">
<!-- Generic page styles -->
<link href="{{url('dist/css/style.css')}}" rel="stylesheet">

resources/views/layouts/admin/partial/layout-js.blade.php
<script src="{{url('vendor/jquery/jquery.min.js')}}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{ url('jBox/Source/jBox.js') }}"></script>
<!-- jBox JavaScript -->
<script src="{{url('dist/js/vendor/jquery.ui.widget.js')}}"></script>
<script src="{{url('dist/js/load-image.all.min.js')}}"></script>

<script src="{{url('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="{{url('vendor/metisMenu/metisMenu.min.js')}}"></script>
  <!-- Custom Theme JavaScript -->
<script src="{{url('dist/js/sb-admin-2.js')}}"></script>
<script src="{{ url('ckeditor/ckeditor.js') }}"></script>
<script src="{{url('panel/data-table/js/jquery.dataTables.min.js')}}" type="text/javascript"></script>

<!-- all javaScript work related to project dynamically-->
<script src="{{url('js/partial-js.js')}}"></script>

<script>
    $(document).ready(function () {
        $('input:not([type=hidden]):first').focus();

        $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
    })
   
    //$('form input:first').siblings('input[type!="hidden"]:first').hide();
    //$('form:first *:input[type!=hidden]:first').focus();
</script>
<!-- blueimp Gallery script -->
<script src="{{url('dist/js/jquery.blueimp-gallery.min.js')}}"></script>
<script src="{{ url('js/angular/angular.js') }}"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="{{url('dist/js/jquery.iframe-transport.js')}}"></script>
<!-- The basic File Upload plugin -->
<script src="{{url('dist/js/jquery.fileupload.js')}}"></script>
<!-- The File Upload processing plugin -->
<script src="{{url('dist/js/jquery.fileupload-process.js')}}"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="{{url('dist/js/jquery.fileupload-image.js')}}"></script>
<!-- The File Upload validation plugin -->
<script src="{{url('dist/js/jquery.fileupload-validate.js')}}"></script>
<!-- The File Upload Angular JS module -->
<script src="{{url('dist/js/jquery.fileupload-angular.js')}}"></script>
<!-- The main application script -->
<script src="{{url('dist/js/app.js')}}"></script>

resources/views/layouts/admin/partial/panel.blade.php
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-{{ $class or 'default' }}">
            @if (isset($panelTitle))
                <div class="panel-heading">
                    <h3 class="panel-title">
                        {{ $panelTitle}}
                    </h3>
                </div>
            @endif

            @if (isset($panelBody))
                <div class="panel-body">
                    <div class="row">
                        {{ $panelBody }}
                    </div>
                </div>
            @endif

            @if (isset($panelFooter))
                <div class="panel-footer">
                    {{ $panelFooter }}
                </div>
            @endif
        </div>
    </div>
</div>

resources/views/layouts/admin/partial/user-profile-menus.blade.php
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
        <li><a href="{{ url('admin/user').'/'.Auth::user()->id  .'/edit'}}"><i class="fa fa-user fa-fw"></i> User
                Profile</a></li>
        @if(Auth::user()->hasRole('administration'))
            <li><a href="{{route('theme.index') }}"><i class="fa fa-gear fa-fw"></i> Settings</a></li>
        @endif
        <li class="divider"></li>
        <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();"> <i class="fa fa-sign-out fa-fw"></i> Logout
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
</li>